Fix build with nightly
error: failed to load source for dependency `prost`

Caused by:
  Unable to update https://github.com/def-/prost#1dfee4ba

Caused by:
  failed to update submodule `prost-build/third-party/protobuf`

Caused by:
  failed to parse url for submodule `prost-build/third-party/protobuf`: `git@github.com:protocolbuffers/protobuf`